# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universidad',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
